version: '3.8'

volumes:
  n8n-data:

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    ports:
      - 5678:5678
    env_file:
      - .env
    volumes:
      - n8n-data:/home/node/.n8n/nodes
      - ./packages/n8n/dist:/home/node/.n8n/custom
      - ./packages/n8n/data :/home/node/import-data
    networks:
      - n8n-network

networks:
  n8n-network: